name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8 for API
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          cd api/ ; pylint `ls -R|grep .py$|xargs`

      - uses: actions/checkout@v2
      - name: Set up Python 3.8 for Processor
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f processor/requirements.txt ]; then pip install -r processor/requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          cd processor/ ; pylint `ls -R|grep .py$|xargs`

      - uses: actions/checkout@v2
      - name: Set up Python 3.8 for Puller
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f puller/requirements.txt ]; then pip install -r puller/requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          cd puller/ ; pylint `ls -R|grep .py$|xargs`
